// config/seed.js - Seed the database with sample movies
require('dotenv').config();
const mongoose = require('mongoose');
const Movie = require('../models/Movie');
const connectDB = require('./db');

const sampleMovies = [
  {
    tmdbId: 1,
    title: "Inception",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genres: ["Action", "Science Fiction", "Thriller"],
    language: "English",
    releaseYear: 2010,
    rating: 8.8,
    voteCount: 34000,
    posterPath: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Marion Cotillard", "Elliot Page", "Tom Hardy"],
    runtime: 148,
    popularity: 95.5,
    trending: true,
    moods: ["Mind-bending", "Exciting", "Thoughtful"],
    situations: ["Alone", "With Friends"],
    dna: ["Fast-paced", "Cerebral", "Mind-bending", "Intellectual", "Stylized Visuals"]
  },
  {
    tmdbId: 2,
    title: "The Dark Knight",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
    releaseYear: 2008,
    rating: 9.0,
    voteCount: 52000,
    posterPath: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    runtime: 152,
    popularity: 98.2,
    trending: true,
    moods: ["Exciting", "Dark", "Suspenseful"],
    situations: ["Alone", "With Friends"],
    dna: ["Fast-paced", "Dark Tone", "Philosophical", "Gritty Visuals", "Heroic Theme"]
  },
  {
    tmdbId: 3,
    title: "Interstellar",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ["Adventure", "Drama", "Science Fiction"],
    language: "English",
    releaseYear: 2014,
    rating: 8.6,
    voteCount: 38000,
    posterPath: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    runtime: 169,
    popularity: 91.3,
    trending: true,
    moods: ["Thoughtful", "Emotional", "Mind-bending"],
    situations: ["Alone", "With Family"],
    dna: ["Moderate Pacing", "Cerebral", "Emotional Depth", "Grand Visuals", "Existential Themes"]
  },
  {
    tmdbId: 4,
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes a peculiar interest in the wealthy and glamorous Park family and decides to infiltrate their household by posing as unrelated, highly qualified individuals.",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
    releaseYear: 2019,
    rating: 8.5,
    voteCount: 17000,
    posterPath: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    runtime: 132,
    popularity: 85.7,
    trending: true,
    moods: ["Dark", "Suspenseful", "Witty"],
    situations: ["With Friends", "Alone"],
    dna: ["Tight Pacing", "Satirical Tone", "Social Commentary", "Stylized Visuals"]
  },
  {
    tmdbId: 5,
    title: "The Shawshank Redemption",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    genres: ["Drama"],
    language: "English",
    releaseYear: 1994,
    rating: 9.3,
    voteCount: 62000,
    posterPath: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    runtime: 142,
    popularity: 88.4,
    trending: false,
    moods: ["Uplifting", "Emotional", "Thoughtful"],
    situations: ["Alone", "With Friends", "With Family"],
    dna: ["Moderate Pacing", "Heartwarming Tone", "Hopeful Theme", "Character-driven"]
  },
  {
    tmdbId: 6,
    title: "Avengers: Endgame",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    genres: ["Action", "Adventure", "Science Fiction"],
    language: "English",
    releaseYear: 2019,
    rating: 8.4,
    voteCount: 45000,
    posterPath: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    runtime: 181,
    popularity: 97.1,
    trending: true,
    moods: ["Exciting", "Emotional", "Epic"],
    situations: ["With Friends", "With Family"],
    dna: ["Fast-paced", "Heroic Tone", "Blockbuster Visuals", "Spectacle"]
  },
  {
    tmdbId: 7,
    title: "The Grand Budapest Hotel",
    overview: "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
    genres: ["Adventure", "Comedy", "Drama"],
    language: "English",
    releaseYear: 2014,
    rating: 8.1,
    voteCount: 12000,
    posterPath: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/liW0mjvvPhlQAkJEFLmdb5bYKQs.jpg",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan"],
    runtime: 100,
    popularity: 72.3,
    trending: false,
    moods: ["Happy", "Witty", "Whimsical"],
    situations: ["With Friends", "Date Night"],
    dna: ["Fast-paced", "Quirky Tone", "Symmetrical Visuals", "Stylized Visuals"]
  },
  {
    tmdbId: 8,
    title: "Get Out",
    overview: "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness about their reception of him eventually reaches a boiling point.",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "English",
    releaseYear: 2017,
    rating: 7.7,
    voteCount: 14000,
    posterPath: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/zSVzBSSSOAB6teCvbpIABxBbVJM.jpg",
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    runtime: 104,
    popularity: 78.9,
    trending: false,
    moods: ["Scary", "Suspenseful", "Thoughtful"],
    situations: ["With Friends", "Alone"],
    dna: ["Tense Pacing", "Dark Tone", "Social Commentary", "Psychological"]
  },
  {
    tmdbId: 9,
    title: "Spirited Away",
    overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    genres: ["Animation", "Family", "Fantasy"],
    language: "Japanese",
    releaseYear: 2001,
    rating: 8.6,
    voteCount: 19000,
    posterPath: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg",
    director: "Hayao Miyazaki",
    cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
    runtime: 125,
    popularity: 82.6,
    trending: false,
    moods: ["Whimsical", "Emotional", "Happy"],
    situations: ["With Family", "Alone"],
    dna: ["Moderate Pacing", "Magical Tone", "Artistic Visuals", "Coming-of-age Theme"]
  },
  {
    tmdbId: 10,
    title: "Mad Max: Fury Road",
    overview: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshipper, and a drifter named Max.",
    genres: ["Action", "Adventure", "Science Fiction"],
    language: "English",
    releaseYear: 2015,
    rating: 8.1,
    voteCount: 21000,
    posterPath: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/phszHPFPtcO8T0hSCxHCzDCnDRl.jpg",
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    runtime: 120,
    popularity: 84.1,
    trending: false,
    moods: ["Exciting", "Epic", "Dark"],
    situations: ["With Friends"],
    dna: ["Non-stop Pacing", "Gritty Tone", "Action-heavy", "Post-apocalyptic Visuals"]
  },
  {
    tmdbId: 11,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
    releaseYear: 1994,
    rating: 8.9,
    voteCount: 28000,
    posterPath: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2QM528GluxMcAd.jpg",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    runtime: 154,
    popularity: 87.3,
    trending: false,
    moods: ["Witty", "Dark", "Exciting"],
    situations: ["With Friends", "Alone"],
    dna: ["Non-linear Structure", "Stylized Dialogues", "Dark Humor Tone", "Iconic Visuals"]
  },
  {
    tmdbId: 12,
    title: "Dune: Part Two",
    overview: "Paul Atreides unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    genres: ["Action", "Adventure", "Science Fiction"],
    language: "English",
    releaseYear: 2024,
    rating: 8.5,
    voteCount: 8900,
    posterPath: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/eeijXm3553xvuFbkPFkDG6CLCbQ.jpg",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Austin Butler"],
    runtime: 167,
    popularity: 96.4,
    trending: true,
    moods: ["Epic", "Exciting", "Thoughtful"],
    situations: ["With Friends", "Alone"],
    dna: ["Immersive Pacing", "Serious Tone", "Grand Visuals", "Political Themes"]
  },
  {
    tmdbId: 13,
    title: "Oppenheimer",
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    genres: ["Drama", "History", "Thriller"],
    language: "English",
    releaseYear: 2023,
    rating: 8.3,
    voteCount: 21000,
    posterPath: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr.", "Florence Pugh"],
    runtime: 180,
    popularity: 93.7,
    trending: true,
    moods: ["Thoughtful", "Tense", "Biographical"],
    situations: ["Alone", "Date Night"],
    dna: ["Rapid Editing", "Serious Tone", "Historical Accuracy", "Intense Score"]
  },
  {
    tmdbId: 14,
    title: "Everything Everywhere All at Once",
    overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    language: "English",
    releaseYear: 2022,
    rating: 7.8,
    voteCount: 13000,
    posterPath: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/fForB9ib0GrCM8BCmERlRlCNDlN.jpg",
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Jamie Lee Curtis", "Ke Huy Quan"],
    runtime: 139,
    popularity: 88.2,
    trending: true,
    moods: ["Mind-bending", "Witty", "Emotional", "Happy"],
    situations: ["With Family", "With Friends"],
    dna: ["Kinetic Pacing", "Absurdist Humor", "Multiverse Theme", "Emotional Core"]
  },
  {
    tmdbId: 15,
    title: "The Lion King",
    overview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savanna.",
    genres: ["Animation", "Drama", "Family"],
    language: "English",
    releaseYear: 1994,
    rating: 8.5,
    voteCount: 18000,
    posterPath: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/wXsQvli6tWqja51pYxXNG1LFIGV.jpg",
    director: "Roger Allers, Rob Minkoff",
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Nathan Lane"],
    runtime: 88,
    popularity: 80.5,
    trending: false,
    moods: ["Happy", "Emotional", "Heartwarming"],
    situations: ["With Family", "Alone"],
    dna: ["Classic Pacing", "Uplifting Tone", "Animated Visuals", "Coming-of-age Theme"]
  }
];

const seedDatabase = async () => {
  try {
    await connectDB();
    
    // Clear existing movies
    await Movie.deleteMany({});
    console.log('🗑️  Cleared existing movies');
    
    // Insert sample movies
    await Movie.insertMany(sampleMovies);
    console.log(`✅ Seeded ${sampleMovies.length} movies successfully`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
};

seedDatabase();
